### ISSUE TITLE
How to access/reference pages without button in navigation bar

### ISSUE THREAD

**Issue by imkemayer** [R-miss-tastic/website#3]
The "Bibliography" page (/bibliography/) references two pages, /bibliography/biblio_complete/ and /bibliography/biblio_topics/, which are not directly accessible via the navigation bar.
When viewing the website locally via R-Studio these two pages are accessible by clicking on the respective links on the Bibliography page but are not found when deployed on the Netlify server.

**Comment by imkemayer** [comment]
Is there a different/better workaround than pushing the knitted .html files related to the .rmd files that are in the content/ folder? If not, this issue can be closed.

**Comment by njtierney** [comment]
This bibliography section is looking fantastic! Well done, Imke!

I _think_ that this is an issue with relative links, which is kind of covered here: https://bookdown.org/yihui/blogdown/dep-path.html# - Yihui seems to be doing some relative linking here: https://raw.githubusercontent.com/rbind/yihui/master/content/en/2018-09-20-target-blank.md

I think you can instead write these `biblio_complete` and `biblio_topics` as `.Rmarkdown` files instead of `.Rmd` files. This doesn't create `.html` but instead `.md` files. This would mean you wouldn't need to commit the HTML each time. You can read more here: https://bookdown.org/yihui/blogdown/output-format.html about this `.Rmarkdown` format.

Another option would be to split to nav bar, perhaps with a dropdown menu (only if the theme as direct, documented behaviour for this, otherwise don't worry), or by creating two new links on the header "References by Topic" and "Complete References". Although those are long names, so perhaps that won't work either.

**Comment by tuxette** [comment]
In `themes/hugo-theme-bootstrap4-blog/layouts/_default/base_of.html`, we have:
```
<nav class="nav blog-nav">
          <a class="nav-link {{ if .IsHome }}active{{ end }}" href="{{ .Site.BaseURL | absLangURL }}">{{ i18n "home" }}</a>
          {{- $currentPage := . -}}
          {{ range .Site.Menus.navbar }}
          {{ $menuURL := .URL | absLangURL }}
          <a class="nav-link{{ if or ($currentPage.IsMenuCurrent "navbar" .) ($currentPage.HasMenuCurrent "navbar" .) }} active{{end}}" href="{{ .URL }}" title="{{ .Title }}">{{ .Name }}</a>
          {{ end }}
</nav>
```
that is explicitely not compatible with dropdown menus :( Changing that behavior would require to edit the theme (I can maybe manage it but is it worth it?)

**Comment by njtierney** [comment]
A quick note on maintaining the website, ideally you do not alter anything in these two directories:

1. `public`
2. `theme`

Instead of changing the theme in the `themes` folder, you can alter it directly in the layouts folder: https://github.com/R-miss-tastic/website/tree/master/layouts/partials

So in this case you could add a new folder inside `layouts`,  `_default`, and change `base_of.html`.

That said, *should* this be done? I think it's actually fine to leave it as is. These two pages are linked to each other, and are both helpful, I don't think we need to create a new section or change the website.

**Comment by tuxette** [comment]
Probably too much so not worth it.
